# Generated by Django 5.1.1 on 2024-10-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_spotkan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezerwacja_spotkan.topic')),
            ],
            options={
                'verbose_name_plural': 'opisy',
            },
        ),
    ]
